import type { Place, PlaceSearchResult, Trip } from "@/lib/types";

export const demoPlaces: Place[] = [
  {
    id: "p-1",
    fsqPlaceId: "demo-prado",
    cityId: "demo-lisbon-city",
    name: "Prado Mercearia",
    address: "R. das Pedras Negras 2",
    neighborhood: "Baixa",
    category: "Eat",
    note: "Go for a late lunch. Ana says the mushroom toast is non-negotiable.",
    sourceUrl: "https://www.instagram.com/",
    coordinates: [-9.1349, 38.7107],
    saved: true,
    plannedDate: "2026-09-18",
    daySortOrder: 0,
    addedBy: "FM",
  },
  {
    id: "p-2",
    fsqPlaceId: "demo-gulbenkian",
    cityId: "demo-lisbon-city",
    name: "Gulbenkian Garden",
    address: "Av. de Berna 45A",
    neighborhood: "Avenidas Novas",
    category: "See",
    note: "Slow morning, sculpture garden, then coffee nearby.",
    coordinates: [-9.1544, 38.7367],
    saved: true,
    plannedDate: "2026-09-19",
    daySortOrder: 0,
    addedBy: "AS",
  },
  {
    id: "p-3",
    fsqPlaceId: "demo-seagull",
    cityId: "demo-lisbon-city",
    name: "Seagull Method Café",
    address: "R. da Palmeira 23",
    neighborhood: "Príncipe Real",
    category: "Drink",
    note: "Breakfast before walking down to Chiado.",
    sourceUrl: "https://www.tiktok.com/",
    coordinates: [-9.1507, 38.7162],
    saved: true,
    plannedDate: "2026-09-19",
    daySortOrder: 1,
    addedBy: "JK",
  },
  {
    id: "p-4",
    fsqPlaceId: "demo-feira",
    cityId: "demo-lisbon-city",
    name: "Feira da Ladra",
    address: "Campo de Santa Clara",
    neighborhood: "Alfama",
    category: "Shop",
    note: "Tuesday flea market. Look for old Portuguese ceramics.",
    coordinates: [-9.1256, 38.7151],
    saved: true,
    plannedDate: "2026-09-20",
    daySortOrder: 0,
    addedBy: "FM",
  },
  {
    id: "p-5",
    fsqPlaceId: "demo-ponto-final",
    cityId: "demo-lisbon-city",
    name: "Ponto Final",
    address: "R. do Ginjal 72",
    neighborhood: "Almada",
    category: "Eat",
    note: "Book sunset dinner and take the ferry back.",
    coordinates: [-9.1462, 38.6847],
    saved: true,
    plannedDate: "2026-09-21",
    daySortOrder: 0,
    addedBy: "AS",
  },
  {
    id: "p-6",
    fsqPlaceId: "demo-cais-do-sodre",
    cityId: "demo-lisbon-city",
    name: "Cais do Sodre Station",
    address: "Praca do Duque da Terceira",
    neighborhood: "Cais do Sodre",
    category: "Transit",
    note: "Metro, train, and ferry connection for the Almada dinner.",
    coordinates: [-9.1453, 38.7061],
    saved: true,
    plannedDate: "2026-09-21",
    daySortOrder: 1,
    addedBy: "FM",
  },
];

export const demoTrips: Trip[] = [
  {
    id: "lisbon-weekender",
    title: "Lisbon, loosely",
    destination: "Lisbon",
    country: "Portugal",
    dateLabel: "SEP 18—22",
    startDate: "2026-09-18",
    endDate: "2026-09-22",
    cities: [{ id: "demo-lisbon-city", name: "Lisbon", country: "Portugal", startDate: "2026-09-18", endDate: "2026-09-22", sortOrder: 0 }],
    dayNotes: [{ id: "demo-note-1", cityId: "demo-lisbon-city", plannedDate: "2026-09-18", note: "Land, drop bags, and keep dinner close to the hotel.", sortOrder: 0, addedBy: "FM" }],
    flights: [{ id: "demo-flight-lisbon", plannedDate: "2026-09-18", arrivalDate: "2026-09-19", airline: "TAP Air Portugal", flightNumber: "TP 258", departureAirport: "YYZ", arrivalAirport: "LIS", departureTime: "10:15", arrivalTime: "21:30" }],
    hotels: [{ id: "demo-hotel-lisbon", cityId: "demo-lisbon-city", name: "Memmo Alfama", address: "Travessa das Merceeiras 27, Lisbon", coordinates: [-9.1308, 38.7119], startDate: "2026-09-18", endDate: "2026-09-22" }],
    agenda: {
      brief: "Keep the first afternoon loose. Book dinner before the flight and leave room for long coffee stops.",
      dayNotes: [{ id: "demo-agenda-note-1", plannedDate: "2026-09-19", note: "Walk north to south; save the tram for the hill back up." }],
      items: [
        { id: "demo-agenda-item-1", plannedDate: "2026-09-18", startTime: "15:30", placeId: "p-1", title: "Late lunch after check-in", completed: false, sortOrder: 0 },
        { id: "demo-agenda-item-2", plannedDate: "2026-09-21", startTime: "19:00", placeId: "p-5", title: "Sunset dinner reservation", completed: false, sortOrder: 0 },
        { id: "demo-agenda-item-3", plannedDate: null, startTime: null, placeId: null, title: "Download the offline map", completed: true, sortOrder: 0 },
      ],
    },
    places: demoPlaces,
    collaborators: [
      { id: "demo-user", name: "Faiz", email: "demo@roamboard.app" },
      { id: "demo-ana", name: "Ana", email: "ana@roamboard.app" },
      { id: "demo-jon", name: "Jon", email: "jon@roamboard.app" },
    ],
  },
  {
    id: "kyoto-after-dark",
    title: "Kyoto after dark",
    destination: "Kyoto",
    country: "Japan",
    dateLabel: "NOV 03—09",
    startDate: "2026-11-03",
    endDate: "2026-11-09",
    cities: [{ id: "demo-kyoto-city", name: "Kyoto", country: "Japan", startDate: "2026-11-03", endDate: "2026-11-09", sortOrder: 0 }],
    dayNotes: [],
    flights: [],
    hotels: [],
    agenda: { brief: "", dayNotes: [], items: [] },
    places: demoPlaces.slice(0, 3),
    collaborators: [{ id: "demo-user", name: "Faiz", email: "demo@roamboard.app" }],
  },
  {
    id: "montreal-summer",
    title: "Montréal, no agenda",
    destination: "Montréal",
    country: "Canada",
    dateLabel: "JUL 10—13",
    startDate: "2027-07-10",
    endDate: "2027-07-13",
    cities: [{ id: "demo-montreal-city", name: "Montréal", country: "Canada", startDate: "2027-07-10", endDate: "2027-07-13", sortOrder: 0 }],
    dayNotes: [],
    flights: [],
    hotels: [],
    agenda: { brief: "", dayNotes: [], items: [] },
    places: demoPlaces.slice(0, 4),
    collaborators: [
      { id: "demo-user", name: "Faiz", email: "demo@roamboard.app" },
      { id: "demo-rae", name: "Rae", email: "rae@roamboard.app" },
    ],
  },
];

export const demoSearchResults: PlaceSearchResult[] = [
  ...demoPlaces.map(({ fsqPlaceId, name, address, neighborhood, coordinates, category }) => ({
    fsqPlaceId,
    name,
    address,
    neighborhood,
    coordinates,
    category,
  })),
  {
    fsqPlaceId: "demo-manteigaria",
    name: "Manteigaria",
    address: "R. do Loreto 2",
    neighborhood: "Chiado",
    coordinates: [-9.1438, 38.7107],
    category: "Eat",
  },
  {
    fsqPlaceId: "demo-fabrica",
    name: "Fábrica Coffee Roasters",
    address: "R. das Portas de Santo Antão 136",
    neighborhood: "Rossio",
    coordinates: [-9.1409, 38.7164],
    category: "Drink",
  },
];

export function getTrip(id: string) {
  return demoTrips.find((trip) => trip.id === id) ?? demoTrips[0];
}
