import type { Place, PlaceSearchResult, Trip } from "@/lib/types";

export const demoPlaces: Place[] = [
  {
    id: "p-1",
    fsqPlaceId: "demo-joes-pizza",
    cityId: "demo-nyc-city",
    name: "Joe’s Pizza",
    address: "7 Carmine St",
    neighborhood: "West Village",
    category: "Eat",
    note: "Go late — the line looks long and never is.",
    sourceUrl: "https://www.instagram.com/",
    coordinates: [-74.0027, 40.7305],
    saved: true,
    plannedDate: "2026-04-10",
    daySortOrder: 0,
    addedBy: "FM",
  },
  {
    id: "p-2",
    fsqPlaceId: "demo-washington-square",
    cityId: "demo-nyc-city",
    name: "Washington Square Park",
    address: "Washington Square",
    neighborhood: "Greenwich Village",
    category: "See",
    note: "Start here. Chess tables, and someone always at the piano.",
    coordinates: [-73.9973, 40.7308],
    saved: true,
    plannedDate: "2026-04-11",
    daySortOrder: 0,
    addedBy: "AS",
  },
  {
    id: "p-3",
    fsqPlaceId: "demo-caffe-reggio",
    cityId: "demo-nyc-city",
    name: "Caffè Reggio",
    address: "119 MacDougal St",
    neighborhood: "Greenwich Village",
    category: "Drink",
    note: "The corner table, before it gets loud.",
    sourceUrl: "https://www.tiktok.com/",
    coordinates: [-73.9997, 40.73],
    saved: true,
    plannedDate: "2026-04-11",
    daySortOrder: 1,
    addedBy: "JK",
  },
  {
    id: "p-4",
    fsqPlaceId: "demo-chelsea-market",
    cityId: "demo-nyc-city",
    name: "Chelsea Market",
    address: "75 Ninth Ave",
    neighborhood: "Chelsea",
    category: "Shop",
    note: "Go hungry, leave with olive oil.",
    coordinates: [-74.0061, 40.7424],
    saved: true,
    plannedDate: "2026-04-12",
    daySortOrder: 0,
    addedBy: "FM",
  },
  {
    id: "p-5",
    fsqPlaceId: "demo-balthazar",
    cityId: "demo-nyc-city",
    name: "Balthazar",
    address: "80 Spring St",
    neighborhood: "SoHo",
    category: "Eat",
    note: "Book the late seating and walk back through SoHo.",
    coordinates: [-73.9982, 40.7226],
    saved: true,
    plannedDate: "2026-04-12",
    daySortOrder: 1,
    addedBy: "AS",
  },
  {
    id: "p-6",
    fsqPlaceId: "demo-14th-8th",
    cityId: "demo-nyc-city",
    name: "14 St – 8 Av Station",
    address: "W 14th St & 8th Ave",
    neighborhood: "Chelsea",
    category: "Transit",
    note: "A, C, E and L lines — the interchange for everything above 14th.",
    coordinates: [-74.0021, 40.7404],
    saved: true,
    plannedDate: "2026-04-12",
    daySortOrder: 2,
    addedBy: "FM",
  },
];

export const demoTrips: Trip[] = [
  {
    id: "nyc-weekender",
    title: "New York, loosely",
    destination: "New York",
    country: "United States",
    dateLabel: "APR 10—13",
    startDate: "2026-04-10",
    endDate: "2026-04-13",
    cities: [{ id: "demo-nyc-city", name: "New York", country: "United States", startDate: "2026-04-10", endDate: "2026-04-13", sortOrder: 0 }],
    dayNotes: [{ id: "demo-note-1", cityId: "demo-nyc-city", plannedDate: "2026-04-10", note: "Land, drop bags, and keep dinner walkable from the hotel.", sortOrder: 0, addedBy: "FM" }],
    flights: [{ id: "demo-flight-nyc", plannedDate: "2026-04-10", arrivalDate: "2026-04-10", airline: "Air Canada", flightNumber: "AC 704", departureAirport: "YYZ", arrivalAirport: "LGA", departureTime: "08:00", arrivalTime: "09:35" }],
    hotels: [{ id: "demo-hotel-nyc", name: "The Jane Hotel", address: "113 Jane St, New York", coordinates: [-74.0094, 40.7382], cityId: "demo-nyc-city", startDate: "2026-04-10", endDate: "2026-04-13" }],
    agenda: {
      brief: "Keep the first afternoon loose. Book the SoHo dinner before the flight and leave room for long coffee stops.",
      dayNotes: [{ id: "demo-agenda-note-1", plannedDate: "2026-04-11", note: "Walk the Village end to end; save the subway for the run up to Chelsea." }],
      items: [
        { id: "demo-agenda-item-1", plannedDate: "2026-04-10", startTime: "15:30", placeId: "p-1", title: "Late slice after check-in", completed: false, sortOrder: 0 },
        { id: "demo-agenda-item-2", plannedDate: "2026-04-12", startTime: "21:00", placeId: "p-5", title: "Late dinner reservation", completed: false, sortOrder: 0 },
        { id: "demo-agenda-item-3", plannedDate: null, startTime: null, placeId: null, title: "Download the offline map", completed: true, sortOrder: 0 },
      ],
    },
    places: demoPlaces,
    collaborators: [
      { id: "demo-user", name: "Faiz", email: "demo@tripboard.app", role: "owner" },
      { id: "demo-ana", name: "Ana", email: "ana@tripboard.app", role: "editor" },
      { id: "demo-jon", name: "Jon", email: "jon@tripboard.app", role: "editor" },
    ],
  },
  {
    id: "kyoto-after-dark",
    title: "Kyoto after dark",
    destination: "Kyoto",
    country: "Japan",
    dateLabel: "NOV 03—09",
    startDate: "2026-11-03",
    endDate: "2026-11-09",
    cities: [{ id: "demo-kyoto-city", name: "Kyoto", country: "Japan", startDate: "2026-11-03", endDate: "2026-11-09", sortOrder: 0 }],
    dayNotes: [],
    flights: [],
    hotels: [],
    agenda: { brief: "", dayNotes: [], items: [] },
    places: demoPlaces.slice(0, 3),
    collaborators: [{ id: "demo-user", name: "Faiz", email: "demo@tripboard.app", role: "owner" }],
  },
  {
    id: "montreal-summer",
    title: "Montréal, no agenda",
    destination: "Montréal",
    country: "Canada",
    dateLabel: "JUL 10—13",
    startDate: "2027-07-10",
    endDate: "2027-07-13",
    cities: [{ id: "demo-montreal-city", name: "Montréal", country: "Canada", startDate: "2027-07-10", endDate: "2027-07-13", sortOrder: 0 }],
    dayNotes: [],
    flights: [],
    hotels: [],
    agenda: { brief: "", dayNotes: [], items: [] },
    places: demoPlaces.slice(0, 4),
    collaborators: [
      { id: "demo-user", name: "Faiz", email: "demo@tripboard.app", role: "owner" },
      { id: "demo-rae", name: "Rae", email: "rae@tripboard.app", role: "editor" },
    ],
  },
];

export const demoSearchResults: PlaceSearchResult[] = [
  ...demoPlaces.map(({ fsqPlaceId, name, address, neighborhood, coordinates, category }) => ({
    fsqPlaceId,
    name,
    address,
    neighborhood,
    coordinates,
    category,
  })),
  {
    fsqPlaceId: "demo-russ-daughters",
    name: "Russ & Daughters",
    address: "179 E Houston St",
    neighborhood: "Lower East Side",
    coordinates: [-73.9881, 40.7223],
    category: "Eat",
  },
  {
    fsqPlaceId: "demo-stumptown",
    name: "Stumptown Coffee Roasters",
    address: "18 W 29th St",
    neighborhood: "NoMad",
    coordinates: [-73.988, 40.7457],
    category: "Drink",
  },
];

export function getTrip(id: string) {
  return demoTrips.find((trip) => trip.id === id) ?? demoTrips[0];
}
